### PR TITLE
Daria

### PR DESCRIPTION
**Pull request by DariaSavchenko12**
code from week_1

### CODE REVIEW

**Review by Ihor0777 — COMMENTED** [review]
Hey, it seems like everyone is following this kind of folder structure, I might be mistaken but it shows me two different folders from source on your end.
Screenshot 2024-05-30 174812
Screenshot 2024-05-30 175113

**Comment by DariaSavchenko12** [comment]
Got it.

**Review by Ihor0777 — APPROVED** [review]
Looks good, thanks.

**Comment by robertiele1040** [comment]
Looks good

**Comment by DariaSavchenko12** [comment]
Hey , why my pull request is closed?

**Comment by feyzanurdogan** [comment]
Looking very good

**Review by feyzanurdogan — APPROVED** [review]

**Comment by robertiele1040** [comment]
@DariaSavchenko12 I always have only two options "Comment and close pull request" or "comment". So I'm not quite sure what I'm supposed to do other, lol. I do check codes if it looks good, I comment and close. Isn't how it's supposed to go? I don't have like "approve" button.

**Comment by DariaSavchenko12** [comment]
@robertiele1040  You may choose to close a pull request without  merging in into upstream branch . In this case its good when changes proposed in the branch are no  longer needed, or if another solution has been proposed in another branch. 
But regarding my case, i wanted to merge my branch into master , and so when you closed pull request  from your end, i wasn't able to merge my branch into upstream.

**Comment by robertiele1040** [comment]
@DariaSavchenko12 I understand that you wanted to merge, I just do not understand how to approve that for you, when I am assigned, since I do not get this option, or I'm missing something here. I attach photo of what options I get. Maybe somebody else knows too ? Should I only do "comment" ?
Screenshot 2024-05-31 at 4 29 29 PM

**Comment by robertiele1040** [comment]
@DariaSavchenko12 OK figured out finally, I was supposed to go to another window. Need to practice on this github more :)

**Comment by DariaSavchenko12** [comment]
@robertiele1040  In this  case you can do only to comment, since you don't have a merge pull request button. Yes, Git its not easy to understand at first, but i think its good that we are practicing here, making mistakes and learning from them. I did brake my code yesterday  , but im glad that it happened cause now i know how to fix it)))

**Comment by Ihor0777** [comment]
Screenshot 2024-05-31 165252

**Pull request merged**
