### PR TITLE
Zina

### PR DESCRIPTION
**Pull request by untuzina**

### CODE REVIEW

**Review by stars2026 — APPROVED** [review]

**Review by stars2026 — APPROVED** [review]

**Comment by feyzanurdogan** [comment]
good

**Review by OlesMykola — APPROVED** [review]
looks good to me

**Review by Ihor0777 — COMMENTED** [review]
It seems to me that approving these changes will delete Sureyya's work, please correct me if I am wrong, also your name folder should be directly from src 
Screenshot 2024-05-30 1805

**Comment by feyzanurdogan** [comment]
Looks good

**Pull request merged**
